intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{eve}: {hxx ixx txx}{** -version} hxx{version} $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

# Export options.
#
lib{eve}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the eve/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/eve/
  install.subdirs = true
}
