import dependencies = eve%lib{eve} libboost-math%lib{boost_math}

# for cpp_file : cxx{** -src/exhaustive/** -src/random/**}
# {
# 	target_name = "$name($cpp_file)"
# 	info "target_name = $target_name"
# 	./ : exe{$target_name} : $cpp_file $dependencies
# }

for cpp_file : src/unit/arch/cxx{**} src/unit/meta/cxx{**} src/unit/internals/cxx{**} src/unit/memory/cxx{**}
{
	target_name = "$name($cpp_file)"
	# info "target_name = $target_name"
	./ : exe{$target_name} : $cpp_file $dependencies
}

cxx.poptions =+ "-I$src_root/src"

