import eve = eve%lib{eve}

for cpp_file : cxx{** -src/multi-arch/** -test/**}
{
	target_name = "$name($cpp_file)"
	info "target_name = $target_name"
	./ : exe{$target_name} : $cpp_file $eve
}

cxx.poptions =+ "-I$src_root/src" "-I$src_root/test"

